name: wheatfspm_dev
channels:
  - conda-forge
  - openalea3
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - openalea.mtg
  - openalea.plantgl
  - openalea.lpy
  - openalea.Caribu
  - openalea.adel
  - openalea.astk
  - pip
  - pip:
      - -e '..[test,dev,doc]'
