{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set license = pyproject.get('project').get('license') %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  string: py{{ PY_VER }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}

  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}


test:
  requires:
    - numpy
    - pandas
    - pytest
    - nbmake
    - scipy
    - alinea.adel # will probably change to openalea.adel
#  imports:
#    - openalea.wheatfspm
  source_files:
    - test/**
  commands:
    - cd test/test_elongwheat && pytest -v
#    - cd ../test_cnwheat && pytest -v
    - cd ../test_farquharwheat && pytest -v
#    - cd ../test_fspmwheat && pytest -v
    - cd ../test_growthwheat && pytest -v
#    - cd ../test_respiwheat && pytest -v
    - cd ../test_senescwheat && pytest -v


about:
  home: {{ home }}
  summary: {{ description }}
  license: {{ license }}

extra:
  recipe-maintainers:
    - rbarillot
